### PR TITLE
Preserve App, Package and Directory addresses

### LINKED ISSUE #35: Preserve App, Package, and Directory addresses in aborted deployments
Given an initial `zos push` operation that deploys Factory, App, Package, and Directory contracts, we want to preserve them as they are being deployed, in case the deployment fails mid-run. Make sure the addresses of each contract is stored in the zos.network.json file as they are deployed, and that the push picks up from there on subsequent operations.

Related to https://github.com/zeppelinos/zos-cli/issues/319

### PR DESCRIPTION
**Pull request by jcarpanelli**
Fixes #35
- [x] Implement an app, package and directory address tracker in lib and cli.
- [x] Pick up already deployed contracts addresses on  future `push` runs.

### CODE REVIEW

File: packages/lib/src/project/AppProject.js [hunk 1]
```diff
@@ -1,26 +1,36 @@
...
+
+      if (!await app.hasPackage(name, version)) await app.setPackage(name, thepackage.address, version)
+      const project = new this(app, name, version, txParams)
+      project.directory = directory
+      project.package = thepackage
+
+      return project
+    } catch(deployError) {
+      throw new DeployError(deployError.message, { thepackage, directory, app })
+    }
```
Comment (facuspagnuolo) [inline packages/lib/src/project/AppProject.js]: What do you think about splitting this method a bit to sth like:
```js
  static async fetchOrDeploy(name = 'main', version = '0.1.0', txParams = {}, { appAddress = undefined, packageAddress = undefined }) {
    try {
      const app = await this.fetchOrDeployApp(...)
      const thepackage = await this.fetchOrDeployPackage(...)
      const directory = await this.fetchOrDeployDirectory(...)
      return this.buildProject(...)
    } catch(deployError) {
      throw new DeployError(deployError.message, { thepackage, directory, app })
    }
  }
```

File: packages/lib/src/project/LibProject.js [hunk 2]
```diff
@@ -1,18 +1,30 @@
...
+        ? await thepackage.getDirectory(version)
+        : await thepackage.newVersion(version)
+
+      const project = new this(thepackage, version, txParams)
+      project.directory = directory
+
+      return project
+    } catch(deployError) {
+      throw new DeployError(deployError.message, { thepackage, directory })
+    }
```
Comment (facuspagnuolo) [inline packages/lib/src/project/LibProject.js]: we may want to split this one too, it is not that large tho

File: packages/cli/src/models/network/NetworkBaseController.js [hunk 3]
```diff
@@ -51,38 +51,38 @@ export default class NetworkBaseController {
...
 
     await Promise.all([
-      this.uploadContracts(reupload), 
+      this.uploadContracts(reupload),
       this.unsetContracts()
     ])
   }
 
-  async pushVersion() {
+  _checkVersion() {
```
Comment (facuspagnuolo) [inline packages/cli/src/models/network/NetworkBaseController.js]: 👍

File: packages/lib/src/project/AppProject.js [hunk 4]
```diff
@@ -1,26 +1,36 @@
...
-  static async deploy(name = 'main', version = '0.1.0', txParams = {}) {
-    const thepackage = await Package.deploy(txParams)
-    const directory = await thepackage.newVersion(version)
-    const app = await App.deploy(txParams)
-    await app.setPackage(name, thepackage.address, version)
-    const project = new this(app, name, version, txParams)
-    project.directory = directory
-    project.package = thepackage
-    return project
+  static async fetchOrDeploy(name = 'main', version = '0.1.0', txParams = {}, { appAddress = undefined, packageAddress = undefined }) {
```
[the remark this answers is not in the document]
Comment (spalladino) [reply packages/lib/src/project/AppProject.js]: I'd say so, it simplifies usage of the Project class directly

**Comment by spalladino** [comment]
@jcarpanelli feel free to merge after applying @facuspagnuolo's suggestions

File: packages/lib/src/project/AppProject.js (hunk 1 above)
Comment (jcarpanelli) [reply packages/lib/src/project/AppProject.js]: We've discussed this offline. It's not a good idea to merge `deploy` and `fetch` methods in `Package` and `App`, as it would add complexity. 
On the other hand, separating the logic to new static methods inside `AppProject`/`LibProject` (or `BasePackageProject`) just to make the code prettier is not reason enough to do so. In case we would want to provide this methods through `zos-lib`, we can add them, but this exceeds this PR's scope.
