### PR TITLE
Skip validation errors upon push force

### LINKED ISSUE #755: Skip errors during contracts validation if force is supplied
There are several errors that occur during contracts validation that are related to incorrect artifacts compilations (such as #465). We should try-catch the validation of every contract, warn the user if an error occured during the process, and allow them to proceed with the `zos push` if `--force` was included (or prompt on whether to continue if in interactive mode).

### PR DESCRIPTION
**Pull request by spalladino**
Fixes #755

### CODE REVIEW

File: packages/cli/src/models/network/NetworkController.ts [hunk 1]
```diff
@@ -210,10 +210,9 @@ export default class NetworkController {
       await this._setSolidityLibs(contract);
       log.info(`Uploading ${contract.schema.contractName} contract as ${contractAlias}`);
       const contractInstance = await this.project.setImplementation(contract, contractAlias);
+      const { types, storage } = contract.schema.storageInfo || { types: null, storage: null };
```
Comment (jcarpanelli) [inline packages/cli/src/models/network/NetworkController.ts]: If there's no difference between having `type` and `storage` assigned as `undefined` instead of `null`, you can simply change this to:
```suggestion
      const { types, storage } = contract.schema.storageInfo;
```

File: packages/lib/src/utils/Logger.ts [hunk 2]
```diff
@@ -36,8 +36,16 @@ export default class Logger {
     this.log(msg, 'yellow');
   }
 
-  public error(msg: string): void {
-    this.log(msg, 'red');
+  public error(msg: string, ex?: Error): void {
```
Comment (jcarpanelli) [inline packages/lib/src/utils/Logger.ts]: :+1:

File: packages/cli/src/models/network/NetworkController.ts (hunk 1 above)
Comment (spalladino) [reply packages/cli/src/models/network/NetworkController.ts]: That was my first try, but actually, the ts compiler complained if I did that
