### PR TITLE
Use require.resolve to lookup contracts in deps

### LINKED ISSUE #1076: Doesn't work with yarn workspaces
I cannot use zos within a monorepo maintained with [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/). I'm getting the following error:

> Could not find a zos.json file for 'openzeppelin-eth'. Make sure it is provided by the npm package.

Workspaces is a feature from yarn that aggregates all common node modules at the root of your repo, but I presume zos is only looking for the relative folder, never above.

I also asked about an alternative solution on StackOverflow, but no one answered: https://stackoverflow.com/questions/56910467/when-using-yarn-workspaces-how-to-force-a-package-to-be-installed-in-the-relati

### PR DESCRIPTION
**Pull request by spalladino**
Change lookup in both Dependency and Contracts classes. Instead of looking for just node_modules in the current folder, it uses require.resolve (relative to the current workdir) to look for the dependency.
    
Fixes #1076

### CODE REVIEW

**Comment by spalladino** [comment]
And here as well! :-)

File: packages/lib/src/artifacts/Contracts.ts [hunk 1]
```diff
@@ -27,6 +28,10 @@ export default class Contracts {
     return path.resolve(Contracts.contractsDir || Contracts.DEFAULT_CONTRACTS_DIR);
   }
 
+  public static getProjectRoot(): string {
+    return path.resolve(this.projectRoot || process.cwd());
```
Comment (jcarpanelli) [inline packages/lib/src/artifacts/Contracts.ts]: :+1: Nice one!
