### PR TITLE
interactive push (first part)

### LINKED ISSUE #707: Interactive prompt to deploy dependencies if they are not present in the current network
If the user is working on a network (such as rinkeby) with an evm package that is not available on that network, then (instead of failing) we should prompt whether they want to deploy that dependency for testing.

If the node is ganache, then deploy anyway without even asking.

### LINKED ISSUE #716: Interactive network params
When the user runs a command that requires a network info (such as create or push), ask which network they want to connect to. Next time the user is prompted about this, default to the latest choice (consider saving it as a session with duration 0 as a hack to implement it).

### PR DESCRIPTION
**Pull request by jcarpanelli**
Fixes #707, fixes #716.

This PR includes:
- Automatic deployment of dependencies if working with `ganache`
- Prompt to deploy dependencies if necessary
- Save last network used for using it as default for next time

interactive-push

EDIT: I also refactored a bit the commands tests. Sorry for doing  this here PR :eyes:

### CODE REVIEW

File: packages/cli/src/models/dependency/Dependency.ts [hunk 1]
```diff
@@ -43,6 +43,20 @@ export default class Dependency {
     }
   }
 
+  public static hasDependenciesForDeploy(network: string): boolean {
+    const dependencies = ZosPackageFile.getLinkedDependencies() || [];
+    const networkDependencies = ZosNetworkFile.getDependencies(`zos.${network}.json`) || {};
+    const hasDependenciesForDeploy = dependencies.find(depNameAndVersion => {
```
Comment (spalladino) [inline packages/cli/src/models/dependency/Dependency.ts]: Can we use `isDeployedOnNetwork`, or a modified version if needed, to avoid remplementing this logic here?

File: packages/cli/src/models/dependency/Dependency.ts [hunk 2]
```diff
@@ -43,6 +43,20 @@ export default class Dependency {
     }
   }
 
+  public static hasDependenciesForDeploy(network: string): boolean {
```
Comment (spalladino) [inline packages/cli/src/models/dependency/Dependency.ts]: How about changing to a `getDependenciesPendingDeployment`, so we can actually show the user a list of the deps that would get deployed? Should be just a matter of changing the `find` to a `filter`.

File: packages/cli/src/models/files/ZosNetworkFile.ts [hunk 3]
```diff
@@ -77,6 +77,11 @@ export default class ZosNetworkFile {
     return file ? file.zosversion : null;
   }
 
+  public static getDependencies(fileName: string): { [key: string]: any } | undefined {
```
Comment (spalladino) [inline packages/cli/src/models/files/ZosNetworkFile.ts]: Can we remove this method, and use something like `packageFile.networkFile(network).dependencies`? I'd assume that networkFile for a new network would yield an empty ZosNetworkFile, that would have empty dependencies as well.

File: packages/cli/src/models/network/Session.ts [hunk 4]
```diff
@@ -14,21 +14,33 @@ interface SessionOptions {
...
 
-  open({ network, from, timeout }: SessionOptions, expires: number = DEFAULT_EXPIRATION_TIMEOUT): void {
+  setDefaultNetworkIfNeeded(network: string): void {
+    const session = this._parseSession();
+    if (!session || this._hasExpired(session)) this.open({ network }, 0, false);
+  },
+
+  getDefaultNetwork(): string | undefined {
+    const session = this._parseSession();
+    return session && this._hasExpired(session) ? session.network : undefined;
```
Comment (spalladino) [inline packages/cli/src/models/network/Session.ts]:
```suggestion
    return session ? session.network : undefined;
```

I think that the session network can still be considered to be the default network regardless of whether it had expired or not.

File: packages/cli/test/commands/push.test.js [hunk 5]
```diff
@@ -1,14 +1,30 @@
...
-  itShouldParse('should call push script with options', 'push', 'zos push --network test --skip-compile -d --reset -f', function(push) {
-    push.should.have.been.calledWithExactly({ force: true, deployDependencies: true, reupload: true, network: 'test', txParams: {} })
-  })
+  context('when network uses ganache', function() {
+    itShouldParse('should call push script with options', 'push', 'zos push --network test --skip-compile -d --reset -f', function(push) {
+      push.should.have.been.calledWithExactly({ force: true, deployDependencies: true, reupload: true, network: 'test', txParams: {} })
+    })
+  });
+
+  context('when network does not use ganache', function () {
```
Comment (spalladino) [inline packages/cli/test/commands/push.test.js]: Awesome

File: packages/cli/test/scripts/session.test.js [hunk 6]
```diff
@@ -11,22 +11,22 @@ describe('session script', function () {
   const opts = { network: 'foo', from: '0x1', timeout: 10 }
 
   describe('opening a new session', function () {
-    describe('when there was no session opened before', function () {
-      describe('when the time out does not expire', function () {
+    context('when there was no session opened before', function () {
```
Comment (spalladino) [inline packages/cli/test/scripts/session.test.js]: Just curious: why this change?

File: tslint.json [hunk 7]
```diff
@@ -49,7 +49,8 @@
       "adjacent-overload-signatures": [false],
       "no-string-literal": [false],
       "max-classes-per-file": [false],
-      "one-variable-per-declaration": [false]
+      "one-variable-per-declaration": [false],
+      "arrow-parens": [false]
```
Comment (spalladino) [inline tslint.json]: I typically dislike a PR that attempts to sneak in a change like this, but since this one is so awesome, I'll look the other way :-P

File: packages/cli/src/models/dependency/Dependency.ts (hunk 1 above)
Comment (jcarpanelli) [reply packages/cli/src/models/dependency/Dependency.ts]: I'll address it in my TODO list, an evaluate in which cases we should stick to class methods and when it's appropriate to instantiate the class.

File: packages/cli/src/models/dependency/Dependency.ts (hunk 2 above)
Comment (jcarpanelli) [reply packages/cli/src/models/dependency/Dependency.ts]: Its a good idea :slightly_smiling_face:

File: packages/cli/test/scripts/session.test.js (hunk 6 above)
Comment (jcarpanelli) [reply packages/cli/test/scripts/session.test.js]: I know that `context` is a synonym for `describe`, but when talking about contexts (*when X is happening*) I prefer using context rather than `describe`. FYI, I started drafting an issue (pending to publish) with a list of conventions we should follow.

File: packages/cli/src/models/network/Session.ts (hunk 4 above)
Comment (jcarpanelli) [reply packages/cli/src/models/network/Session.ts]: Mmmh but if the session hasn't expired, we won't be prompting the network list (and thus we won't show a default network)

Comment (spalladino) [reply packages/cli/src/models/network/Session.ts]: Gotcha! I had understood that this was used not for skipping the prompt, but for providing a default option among the networks listed.
